/*
* generated by Xtext
*/
package org.jsonclipse.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.jsonclipse.services.JsonGrammarAccess;

public class JsonParser extends AbstractContentAssistParser {
	
	@Inject
	private JsonGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.jsonclipse.ui.contentassist.antlr.internal.InternalJsonParser createParser() {
		org.jsonclipse.ui.contentassist.antlr.internal.InternalJsonParser result = new org.jsonclipse.ui.contentassist.antlr.internal.InternalJsonParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getExpAccess().getAlternatives_1(), "rule__Exp__Alternatives_1");
					put(grammarAccess.getIntegerAccess().getAlternatives(), "rule__Integer__Alternatives");
					put(grammarAccess.getNumberAccess().getGroup(), "rule__Number__Group__0");
					put(grammarAccess.getExpAccess().getGroup(), "rule__Exp__Group__0");
					put(grammarAccess.getFracAccess().getGroup(), "rule__Frac__Group__0");
					put(grammarAccess.getIntegerAccess().getGroup_1(), "rule__Integer__Group_1__0");
					put(grammarAccess.getObjectAccess().getGroup(), "rule__Object__Group__0");
					put(grammarAccess.getObjectAccess().getGroup_1(), "rule__Object__Group_1__0");
					put(grammarAccess.getObjectAccess().getGroup_1_1(), "rule__Object__Group_1_1__0");
					put(grammarAccess.getObjectPropertyAccess().getGroup(), "rule__ObjectProperty__Group__0");
					put(grammarAccess.getArrayAccess().getGroup(), "rule__Array__Group__0");
					put(grammarAccess.getArrayAccess().getGroup_1(), "rule__Array__Group_1__0");
					put(grammarAccess.getArrayAccess().getGroup_1_1(), "rule__Array__Group_1_1__0");
					put(grammarAccess.getModelAccess().getRootAssignment(), "rule__Model__RootAssignment");
					put(grammarAccess.getValueAccess().getObjectValueAssignment_3(), "rule__Value__ObjectValueAssignment_3");
					put(grammarAccess.getValueAccess().getArrayValueAssignment_4(), "rule__Value__ArrayValueAssignment_4");
					put(grammarAccess.getValueAccess().getNumberValueAssignment_5(), "rule__Value__NumberValueAssignment_5");
					put(grammarAccess.getValueAccess().getStringValueAssignment_6(), "rule__Value__StringValueAssignment_6");
					put(grammarAccess.getObjectAccess().getPropertiesAssignment_1_0(), "rule__Object__PropertiesAssignment_1_0");
					put(grammarAccess.getObjectAccess().getPropertiesAssignment_1_1_1(), "rule__Object__PropertiesAssignment_1_1_1");
					put(grammarAccess.getObjectPropertyAccess().getPropNameAssignment_0(), "rule__ObjectProperty__PropNameAssignment_0");
					put(grammarAccess.getObjectPropertyAccess().getPropValueAssignment_2(), "rule__ObjectProperty__PropValueAssignment_2");
					put(grammarAccess.getArrayAccess().getElementsAssignment_1_0(), "rule__Array__ElementsAssignment_1_0");
					put(grammarAccess.getArrayAccess().getElementsAssignment_1_1_1(), "rule__Array__ElementsAssignment_1_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.jsonclipse.ui.contentassist.antlr.internal.InternalJsonParser typedParser = (org.jsonclipse.ui.contentassist.antlr.internal.InternalJsonParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public JsonGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JsonGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
