/*
* generated by Xtext
*/
package org.jsonclipse;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JsonUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.jsonclipse.ui.internal.JsonActivator.getInstance().getInjector("org.jsonclipse.Json");
	}
	
}
