/*
 * generated by Xtext
 */
package org.jsonclipse.ui.contentassist

import org.jsonclipse.ui.contentassist.AbstractJsonProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class JsonProposalProvider extends AbstractJsonProposalProvider {
}
