/*
 * generated by Xtext
 */
package org.jsonclipse;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonRuntimeModule extends org.jsonclipse.AbstractJsonRuntimeModule {

}
